import { StyleSheet } from 'react-native';

const COLORS = {
    red: '#e60000',
    dark: '#111827',
    white: '#ffffff',
    bgGray: '#f4f5f7',
    inputBg: '#f9fafb',
    borderColor: '#f3f4f6',
    textGray: '#9ca3af',
    textDark: '#4b5563',
    green: '#10b981',
    lightRed: '#fee2e2'
};

export const driverStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.bgGray,
    },
    card: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginHorizontal: 15,
        marginBottom: 20,
        elevation: 4,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
    },
    dashboardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 20,
        backgroundColor: COLORS.white,
        marginBottom: 10,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: COLORS.dark,
    },
    headerSub: {
        fontSize: 12,
        color: COLORS.textGray,
        fontWeight: 'bold',
        marginTop: 4,
    },
    scanBtn: {
        backgroundColor: COLORS.red,
        padding: 25,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        margin: 15,
        elevation: 4,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 20,
        color: COLORS.dark,
    },
    stopItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    stopIcon: {
        width: 40,
        textAlign: 'center',
        marginRight: 15,
    },
    activeStopDot: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.red,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    activeStopNumber: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontSize: 16,
    },
    futureStopDot: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.borderColor,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    futureStopNumber: {
        color: COLORS.textGray,
        fontWeight: 'bold',
        fontSize: 16,
    },
    stopNameDone: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.dark,
        textDecorationLine: 'line-through',
        opacity: 0.5,
    },
    stopNameActive: {
        fontSize: 17,
        fontWeight: 'bold',
        color: COLORS.red,
    },
    stopNameFuture: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.textGray,
    },
    stopTime: {
        color: COLORS.textGray,
        fontSize: 12,
    },
    stopTimeActive: {
        color: COLORS.red,
        fontSize: 12,
        fontWeight: 'bold',
    },
    arriveBtn: {
        backgroundColor: COLORS.dark,
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 10,
    },
    arriveBtnText: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontSize: 14,
    },
    boardingHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    tabs: {
        flexDirection: 'row',
        backgroundColor: COLORS.borderColor,
        borderRadius: 10,
        padding: 4,
    },
    tab: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        fontSize: 12,
        fontWeight: 'bold',
        color: COLORS.textGray,
    },
    tabActive: {
        backgroundColor: COLORS.white,
        color: COLORS.dark,
        borderRadius: 8,
    },
    passengerList: {
        gap: 12,
    },
    passengerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.inputBg,
        padding: 15,
        borderRadius: 15,
    },
    passengerRowPending: {
        backgroundColor: COLORS.white,
        borderWidth: 1,
        borderColor: COLORS.lightRed,
    },
    seatBadge: {
        backgroundColor: COLORS.borderColor,
        width: 45,
        height: 45,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    seatText: {
        fontWeight: 'bold',
        color: COLORS.textDark,
    },
    passengerName: {
        fontWeight: 'bold',
        color: COLORS.dark,
        fontSize: 15,
    },
    passengerDetails: {
        fontSize: 11,
        color: COLORS.textGray,
        marginTop: 2,
    },
    manualBtn: {
        backgroundColor: COLORS.dark,
        paddingHorizontal: 15,
        paddingVertical: 10,
        borderRadius: 10,
    },
    manualBtnText: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontSize: 11,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: COLORS.inputBg,
        padding: 20,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: COLORS.borderColor,
        marginBottom: 15,
    },
    inputWrapperActive: {
        borderColor: COLORS.red,
        backgroundColor: COLORS.white,
    },
    textInput: {
        fontSize: 32,
        fontWeight: 'bold',
        color: COLORS.dark,
        flex: 1,
    },
    submitBtn: {
        backgroundColor: COLORS.dark,
        padding: 22,
        borderRadius: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    submitBtnText: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontSize: 16,
        letterSpacing: 1,
    },
    cameraContainer: {
        flex: 1,
        backgroundColor: '#000',
    }
});